---
- hosts: localhost
  connection: local

  tasks:
    - name: init git submodules locally
      command: git submodule init

    - name: update git submodules locally
      command: git submodule update

    - name: checkout submodules
      command: git submodule foreach git checkout master

    - name: pull submodules
      command: git submodule foreach git pull origin master


- hosts: all
  become: true

  vars:
      home_server_install_path: '/opt/home-server'
      non_root_user: 'rjm'

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg2
          - wget
          - software-properties-common
          - rsync
          - python3-docker
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present

    - name: Add Terraform GPG apt Key
      shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

    - name: Add Terraform Repository
      shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Terraform installation
      apt:
        name: terraform
        state: latest
        update_cache: true

    - name: Ensure docker deamon is running as a service
      service:
        name: docker
        state: started

    - name: Sync files
      synchronize:
        src: ./
        dest: '{{ home_server_install_path }}'
        delete: yes
        rsync_path: /usr/bin/rsync
        rsync_opts:
          - "--exclude=*.tfstate*"
          - "--exclude=*.terraform*"

    - name: Creates directory
      ansible.builtin.file:
        path: '{{ home_server_install_path }}/data'
        state: directory

    - name: Change synced files ownership
      file:
        path: '{{ home_server_install_path }}'
        recurse: true
        owner: '{{ non_root_user }}'

    - name: Copy allowed_origins.cfg, before building multiple pony image
      ansible.builtin.copy:
        src: 'allowed_origins.cfg'
        dest: '{{ home_server_install_path }}/MultiplePony/server/'

    - name: Copy audio files, before building multiple pony image
      ansible.builtin.copy:
        src: 'audio'
        dest: '{{ home_server_install_path }}/MultiplePony/server/public/'

    - name: Build multiple pony image
      community.docker.docker_image:
        name: multiple-pony:latest
        build:
          path: '{{ home_server_install_path }}/MultiplePony/server'
          nocache: true
        source: build
        force_source: true

    - name: Terraform init
      ansible.builtin.command: terraform init
      become: true
      become_user: '{{ non_root_user }}'
      args:
        chdir: '{{ home_server_install_path }}'

    - name: Terraform apply
      ansible.builtin.command: terraform apply -var-file="lenovo-ssf/terraform.tfvars" -auto-approve
      become: true
      become_user: '{{ non_root_user }}'
      args:
        chdir: '{{ home_server_install_path }}'