---
- hosts: local
  hosts: localhost
  connection: local
  tasks:

    - name: Build finance project
      command:
        cmd: ./gradlew build
        chdir: ../Java/finance

- hosts: all
  become: yes
  become_user: root
  tasks:

    - debug: msg="Ansible running in {{ansible_lsb.id}}!"

    # - name: Install git
    #   apt:
    #     name: git
    #     state: present
    #     update_cache: yes
    #
    # - name: Install java
    #   apt:
    #     name: openjdk-8-jre
    #     state: present
    #     update_cache: yes

    - name: Sync finance app
      copy:
        src: ../Java/finance/build/libs/finance-0.0.1-SNAPSHOT.jar
        dest: /opt/finance-0.0.1-SNAPSHOT.jar
