---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - debug: msg="Ansible running in {{ansible_lsb.id}}!"
    - name: Install awscli
      pip:
        name: awscli
        executable: pip3
